# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\forno_design.ui'
#
# Created: Sun Jun 07 02:06:31 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(801, 617)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 641, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 201, 22))
        self.horizontalSlider.setMinimum(-99)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_7.setGeometry(QtCore.QRect(130, 50, 71, 31))
        self.lcdNumber_7.setNumDigits(3)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 50, 71, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 90, 221, 161))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalSlider_6 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_6.setEnabled(False)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(150, 90, 61, 21))
        self.horizontalSlider_6.setMaximum(1)
        self.horizontalSlider_6.setSingleStep(1)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_6.setTickInterval(100)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.horizontalSlider_3 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_3.setEnabled(False)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.horizontalSlider_3.setMaximum(1)
        self.horizontalSlider_3.setSingleStep(1)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.horizontalSlider_5 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_5.setEnabled(False)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(80, 40, 61, 21))
        self.horizontalSlider_5.setMaximum(1)
        self.horizontalSlider_5.setSingleStep(1)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.horizontalSlider_2 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_2.setEnabled(False)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.horizontalSlider_2.setMaximum(1)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalSlider_4 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_4.setEnabled(False)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(80, 90, 61, 21))
        self.horizontalSlider_4.setMaximum(1)
        self.horizontalSlider_4.setSingleStep(1)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 0)
        self.horizontalSlider_4.setSliderPosition(0)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.horizontalSlider_7 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_7.setEnabled(False)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(150, 40, 61, 21))
        self.horizontalSlider_7.setMaximum(1)
        self.horizontalSlider_7.setSingleStep(1)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 56, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(80, 130, 56, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 56, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(80, 70, 56, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(150, 70, 56, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber_8 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_8.setGeometry(QtCore.QRect(130, 120, 71, 31))
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(10, 120, 82, 21))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 250, 221, 221))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 50, 221, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textEdit = QtGui.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.widget = matplotlibWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(230, 50, 391, 351))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(250, 10, 85, 18))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(250, 30, 85, 18))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 30, 85, 18))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(330, 10, 85, 18))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(420, 30, 85, 18))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(420, 10, 85, 18))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_8 = QtGui.QCheckBox(self.tab)
        self.checkBox_8.setGeometry(QtCore.QRect(510, 10, 85, 18))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_7 = QtGui.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(510, 30, 85, 18))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.horizontalSlider_8 = QtGui.QSlider(self.tab)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(360, 430, 151, 21))
        self.horizontalSlider_8.setMinimum(1)
        self.horizontalSlider_8.setMaximum(180)
        self.horizontalSlider_8.setProperty("value", 60)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(360, 410, 151, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(360, 450, 41, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(470, 450, 51, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBox_14 = QtGui.QCheckBox(self.tab)
        self.checkBox_14.setEnabled(True)
        self.checkBox_14.setGeometry(QtCore.QRect(520, 420, 51, 18))
        self.checkBox_14.setChecked(False)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(520, 440, 61, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.spinBox_4 = QtGui.QSpinBox(self.tab)
        self.spinBox_4.setGeometry(QtCore.QRect(580, 420, 53, 31))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setSingleStep(1)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 121, 111))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(5000)
        self.spinBox_3.setSingleStep(1)
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 40, 91, 20))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 121, 221))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.spinBox_2.setMinimum(10)
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setProperty("value", 1000)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 20, 121, 61))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 180, 121, 31))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 360, 121, 101))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 20, 121, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(160, 10, 461, 346))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(660, 0, 131, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 20, 131, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 50, 131, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(0, 70, 131, 26))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 131, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 120, 131, 26))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 150, 131, 421))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 30, 111, 41))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setProperty("value", 23.0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setProperty("value", 23.0)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_4.setGeometry(QtCore.QRect(10, 180, 111, 41))
        self.lcdNumber_4.setSmallDecimalPoint(True)
        self.lcdNumber_4.setProperty("value", 23.0)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_6.setGeometry(QtCore.QRect(10, 280, 111, 41))
        self.lcdNumber_6.setSmallDecimalPoint(True)
        self.lcdNumber_6.setProperty("value", 23.0)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 330, 111, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 390, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(70, 370, 53, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 370, 51, 18))
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_5.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.lcdNumber_5.setSmallDecimalPoint(True)
        self.lcdNumber_5.setProperty("value", 23.0)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 130, 111, 41))
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setProperty("value", 23.0)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 500, 411, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.progressBar_3 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_3.setGeometry(QtCore.QRect(290, 20, 118, 23))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.progressBar_6 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_6.setGeometry(QtCore.QRect(10, 20, 118, 23))
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.progressBar_7 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_7.setGeometry(QtCore.QRect(10, 40, 118, 23))
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.progressBar_2 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_2.setGeometry(QtCore.QRect(290, 40, 118, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.progressBar_5 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_5.setGeometry(QtCore.QRect(150, 40, 118, 23))
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.progressBar_4 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_4.setGeometry(QtCore.QRect(150, 20, 118, 23))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 510, 221, 61))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: red"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTeste = QtGui.QMenu(self.menuFile)
        self.menuTeste.setTearOffEnabled(False)
        self.menuTeste.setObjectName(_fromUtf8("menuTeste"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        self.menuComunica_o = QtGui.QMenu(self.menubar)
        self.menuComunica_o.setObjectName(_fromUtf8("menuComunica_o"))
        self.menuPorta_Serial = QtGui.QMenu(self.menuComunica_o)
        self.menuPorta_Serial.setObjectName(_fromUtf8("menuPorta_Serial"))
        self.menuBaudrate = QtGui.QMenu(self.menuComunica_o)
        self.menuBaudrate.setObjectName(_fromUtf8("menuBaudrate"))
        self.menuLatencia = QtGui.QMenu(self.menuComunica_o)
        self.menuLatencia.setObjectName(_fromUtf8("menuLatencia"))
        self.menuDados = QtGui.QMenu(self.menubar)
        self.menuDados.setObjectName(_fromUtf8("menuDados"))
        self.menuExportar_Experimento_como_xls = QtGui.QMenu(self.menuDados)
        self.menuExportar_Experimento_como_xls.setObjectName(_fromUtf8("menuExportar_Experimento_como_xls"))
        self.menuCamera = QtGui.QMenu(self.menubar)
        self.menuCamera.setObjectName(_fromUtf8("menuCamera"))
        self.menuImagem = QtGui.QMenu(self.menuCamera)
        self.menuImagem.setObjectName(_fromUtf8("menuImagem"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTeste2 = QtGui.QAction(MainWindow)
        self.actionTeste2.setObjectName(_fromUtf8("actionTeste2"))
        self.actionParte1 = QtGui.QAction(MainWindow)
        self.actionParte1.setCheckable(False)
        self.actionParte1.setObjectName(_fromUtf8("actionParte1"))
        self.actionParte2 = QtGui.QAction(MainWindow)
        self.actionParte2.setCheckable(False)
        self.actionParte2.setChecked(False)
        self.actionParte2.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionParte2.setObjectName(_fromUtf8("actionParte2"))
        self.actionCOM1 = QtGui.QAction(MainWindow)
        self.actionCOM1.setCheckable(True)
        self.actionCOM1.setObjectName(_fromUtf8("actionCOM1"))
        self.actionCOM2 = QtGui.QAction(MainWindow)
        self.actionCOM2.setCheckable(True)
        self.actionCOM2.setObjectName(_fromUtf8("actionCOM2"))
        self.actionCOM3 = QtGui.QAction(MainWindow)
        self.actionCOM3.setCheckable(True)
        self.actionCOM3.setObjectName(_fromUtf8("actionCOM3"))
        self.action_dev_ttyA0 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA0.setCheckable(True)
        self.action_dev_ttyA0.setChecked(True)
        self.action_dev_ttyA0.setObjectName(_fromUtf8("action_dev_ttyA0"))
        self.action_dev_ttyA1 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA1.setCheckable(True)
        self.action_dev_ttyA1.setObjectName(_fromUtf8("action_dev_ttyA1"))
        self.action9600 = QtGui.QAction(MainWindow)
        self.action9600.setCheckable(True)
        self.action9600.setChecked(True)
        self.action9600.setObjectName(_fromUtf8("action9600"))
        self.actionImportar_dados = QtGui.QAction(MainWindow)
        self.actionImportar_dados.setObjectName(_fromUtf8("actionImportar_dados"))
        self.actionEnviar_Arquivos = QtGui.QAction(MainWindow)
        self.actionEnviar_Arquivos.setObjectName(_fromUtf8("actionEnviar_Arquivos"))
        self.actionVideo = QtGui.QAction(MainWindow)
        self.actionVideo.setObjectName(_fromUtf8("actionVideo"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.action11500 = QtGui.QAction(MainWindow)
        self.action11500.setCheckable(True)
        self.action11500.setObjectName(_fromUtf8("action11500"))
        self.actionExportar_como_csv = QtGui.QAction(MainWindow)
        self.actionExportar_como_csv.setObjectName(_fromUtf8("actionExportar_como_csv"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXLS = QtGui.QAction(MainWindow)
        self.actionXLS.setObjectName(_fromUtf8("actionXLS"))
        self.actionTXT = QtGui.QAction(MainWindow)
        self.actionTXT.setObjectName(_fromUtf8("actionTXT"))
        self.actionNumpy = QtGui.QAction(MainWindow)
        self.actionNumpy.setObjectName(_fromUtf8("actionNumpy"))
        self.action0_5s = QtGui.QAction(MainWindow)
        self.action0_5s.setCheckable(True)
        self.action0_5s.setObjectName(_fromUtf8("action0_5s"))
        self.action1s = QtGui.QAction(MainWindow)
        self.action1s.setCheckable(True)
        self.action1s.setObjectName(_fromUtf8("action1s"))
        self.action1_5s = QtGui.QAction(MainWindow)
        self.action1_5s.setCheckable(True)
        self.action1_5s.setObjectName(_fromUtf8("action1_5s"))
        self.action2s = QtGui.QAction(MainWindow)
        self.action2s.setCheckable(True)
        self.action2s.setChecked(True)
        self.action2s.setObjectName(_fromUtf8("action2s"))
        self.action3s = QtGui.QAction(MainWindow)
        self.action3s.setCheckable(True)
        self.action3s.setObjectName(_fromUtf8("action3s"))
        self.action5s = QtGui.QAction(MainWindow)
        self.action5s.setCheckable(True)
        self.action5s.setObjectName(_fromUtf8("action5s"))
        self.action10s = QtGui.QAction(MainWindow)
        self.action10s.setCheckable(True)
        self.action10s.setObjectName(_fromUtf8("action10s"))
        self.actionCustom = QtGui.QAction(MainWindow)
        self.actionCustom.setObjectName(_fromUtf8("actionCustom"))
        self.actionResolu_o_1 = QtGui.QAction(MainWindow)
        self.actionResolu_o_1.setObjectName(_fromUtf8("actionResolu_o_1"))
        self.actionResolu_o_2 = QtGui.QAction(MainWindow)
        self.actionResolu_o_2.setObjectName(_fromUtf8("actionResolu_o_2"))
        self.actionExclusive = QtGui.QAction(MainWindow)
        self.actionExclusive.setObjectName(_fromUtf8("actionExclusive"))
        self.menuTeste.addAction(self.actionParte1)
        self.menuTeste.addAction(self.actionParte2)
        self.menuFile.addAction(self.menuTeste.menuAction())
        self.menuFile.addAction(self.actionTeste2)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuAjuda.addAction(self.actionManual)
        self.menuPorta_Serial.addSeparator()
        self.menuPorta_Serial.addAction(self.actionCOM1)
        self.menuPorta_Serial.addAction(self.actionCOM2)
        self.menuPorta_Serial.addAction(self.actionCOM3)
        self.menuPorta_Serial.addAction(self.action_dev_ttyA0)
        self.menuPorta_Serial.addAction(self.action_dev_ttyA1)
        self.menuBaudrate.addAction(self.action9600)
        self.menuBaudrate.addAction(self.action11500)
        self.menuLatencia.addAction(self.action0_5s)
        self.menuLatencia.addAction(self.action1s)
        self.menuLatencia.addAction(self.action1_5s)
        self.menuLatencia.addAction(self.action2s)
        self.menuLatencia.addAction(self.action3s)
        self.menuLatencia.addAction(self.action5s)
        self.menuLatencia.addAction(self.action10s)
        self.menuLatencia.addAction(self.actionCustom)
        self.menuComunica_o.addAction(self.menuPorta_Serial.menuAction())
        self.menuComunica_o.addAction(self.menuBaudrate.menuAction())
        self.menuComunica_o.addAction(self.menuLatencia.menuAction())
        self.menuExportar_Experimento_como_xls.addAction(self.actionCSV)
        self.menuExportar_Experimento_como_xls.addAction(self.actionXLS)
        self.menuExportar_Experimento_como_xls.addAction(self.actionTXT)
        self.menuExportar_Experimento_como_xls.addAction(self.actionNumpy)
        self.menuDados.addAction(self.menuExportar_Experimento_como_xls.menuAction())
        self.menuDados.addAction(self.actionImportar_dados)
        self.menuDados.addAction(self.actionEnviar_Arquivos)
        self.menuImagem.addAction(self.actionResolu_o_1)
        self.menuImagem.addAction(self.actionResolu_o_2)
        self.menuCamera.addAction(self.actionVideo)
        self.menuCamera.addAction(self.menuImagem.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComunica_o.menuAction())
        self.menubar.addAction(self.menuDados.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(3)
        self.comboBox_2.setCurrentIndex(3)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_7.display)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Esteira", None))
        self.pushButton_4.setText(_translate("MainWindow", "Parar", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Resistências", None))
        self.label_4.setText(_translate("MainWindow", "Superior", None))
        self.label_5.setText(_translate("MainWindow", "Inferior", None))
        self.label_6.setText(_translate("MainWindow", "Esquerda", None))
        self.label_7.setText(_translate("MainWindow", "Centro", None))
        self.label_8.setText(_translate("MainWindow", "Direita", None))
        self.radioButton.setText(_translate("MainWindow", "Hold", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Comando Manual", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Comandos Manuais", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Dados Ubee", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Temperatura", None))
        self.pushButton_6.setText(_translate("MainWindow", "Envia", None))
        self.checkBox.setText(_translate("MainWindow", "Sensor 1", None))
        self.checkBox_2.setText(_translate("MainWindow", "Sensor 2", None))
        self.checkBox_3.setText(_translate("MainWindow", "Sensor 4", None))
        self.checkBox_4.setText(_translate("MainWindow", "Sensor 3", None))
        self.checkBox_5.setText(_translate("MainWindow", "Sensor 6", None))
        self.checkBox_6.setText(_translate("MainWindow", "Sensor 5", None))
        self.checkBox_8.setText(_translate("MainWindow", "Simulação", None))
        self.checkBox_7.setText(_translate("MainWindow", "Esteira", None))
        self.label_9.setText(_translate("MainWindow", "Intervalo de tempo = 60min", None))
        self.label_10.setText(_translate("MainWindow", "1 min", None))
        self.label_11.setText(_translate("MainWindow", "180 min", None))
        self.checkBox_14.setText(_translate("MainWindow", "Auto", None))
        self.label_16.setText(_translate("MainWindow", "Latência:", None))
        self.pushButton_7.setText(_translate("MainWindow", "LimparTexto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Manual", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Automatico", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Automatico - Imagem", None))
        self.label_14.setText(_translate("MainWindow", "Refresh (s)", None))
        self.checkBox_10.setText(_translate("MainWindow", "Auto update", None))
        self.checkBox_11.setText(_translate("MainWindow", "Auto Save", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Manual - Imagem", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "2592x1944", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "1296x972", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "1296x730", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "640x480", None))
        self.pushButton_5.setText(_translate("MainWindow", "Tira Foto", None))
        self.label_13.setText(_translate("MainWindow", "Delay (ms)", None))
        self.label_12.setText(_translate("MainWindow", "Resolução", None))
        self.pushButton_9.setText(_translate("MainWindow", "Salva Imagem", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "AutoDetecção", None))
        self.pushButton_10.setText(_translate("MainWindow", "Configurações", None))
        self.checkBox_12.setText(_translate("MainWindow", "Auto Detect", None))
        self.checkBox_13.setText(_translate("MainWindow", "Alerta", None))
        self.label_15.setText(_translate("MainWindow", "PI Camera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Camera", None))
        self.groupBox.setTitle(_translate("MainWindow", "Conexão", None))
        self.pushButton.setText(_translate("MainWindow", "Conectar", None))
        self.label.setText(_translate("MainWindow", "Porta:", None))
        self.label_2.setText(_translate("MainWindow", "BaudRate", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "57600", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "115200", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sensores", None))
        self.pushButton_2.setText(_translate("MainWindow", "Atualiza", None))
        self.label_3.setText(_translate("MainWindow", "Latência:", None))
        self.checkBox_9.setText(_translate("MainWindow", "Auto", None))
        self.groupBox_3.setTitle(_translate("MainWindow", " Esquerda                            Potencia Resistências                           Direita", None))
        self.pushButton_3.setText(_translate("MainWindow", "Emergência", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTeste.setTitle(_translate("MainWindow", "Configuração", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.menuComunica_o.setTitle(_translate("MainWindow", "Comunicação", None))
        self.menuPorta_Serial.setTitle(_translate("MainWindow", "Porta Serial", None))
        self.menuBaudrate.setTitle(_translate("MainWindow", "Baudrate", None))
        self.menuLatencia.setTitle(_translate("MainWindow", "Latência", None))
        self.menuDados.setTitle(_translate("MainWindow", "Dados", None))
        self.menuExportar_Experimento_como_xls.setTitle(_translate("MainWindow", "Exportar Experimento", None))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera", None))
        self.menuImagem.setTitle(_translate("MainWindow", "Imagem", None))
        self.actionTeste2.setText(_translate("MainWindow", "Imprimir", None))
        self.actionParte1.setText(_translate("MainWindow", "Salvar Configuração", None))
        self.actionParte2.setText(_translate("MainWindow", "Restaurar Padrão", None))
        self.actionCOM1.setText(_translate("MainWindow", "COM1", None))
        self.actionCOM2.setText(_translate("MainWindow", "COM2", None))
        self.actionCOM3.setText(_translate("MainWindow", "COM3", None))
        self.action_dev_ttyA0.setText(_translate("MainWindow", "/dev/ttyA0", None))
        self.action_dev_ttyA1.setText(_translate("MainWindow", "/dev/ttyA1", None))
        self.action9600.setText(_translate("MainWindow", "9600", None))
        self.actionImportar_dados.setText(_translate("MainWindow", "Importar dados", None))
        self.actionEnviar_Arquivos.setText(_translate("MainWindow", "Enviar Arquivos", None))
        self.actionVideo.setText(_translate("MainWindow", "Video", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.action11500.setText(_translate("MainWindow", "11500", None))
        self.actionExportar_como_csv.setText(_translate("MainWindow", "Exportar como csv", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionXLS.setText(_translate("MainWindow", "XLS", None))
        self.actionTXT.setText(_translate("MainWindow", "TXT", None))
        self.actionNumpy.setText(_translate("MainWindow", "Numpy", None))
        self.action0_5s.setText(_translate("MainWindow", "0.5s", None))
        self.action1s.setText(_translate("MainWindow", "1s", None))
        self.action1_5s.setText(_translate("MainWindow", "1.5s", None))
        self.action2s.setText(_translate("MainWindow", "2s", None))
        self.action3s.setText(_translate("MainWindow", "3s", None))
        self.action5s.setText(_translate("MainWindow", "5s", None))
        self.action10s.setText(_translate("MainWindow", "10s", None))
        self.actionCustom.setText(_translate("MainWindow", "Outro ...", None))
        self.actionResolu_o_1.setText(_translate("MainWindow", "Resolução 1", None))
        self.actionResolu_o_2.setText(_translate("MainWindow", "Resolução 2", None))
        self.actionExclusive.setText(_translate("MainWindow", "exclusive", None))

from matplotlibwidgetFile import matplotlibWidget
