# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/forno_design.ui'
#
# Created: Sat Sep 17 02:56:52 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(807, 607)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 641, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalSlider_esteira = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider_esteira.setEnabled(False)
        self.horizontalSlider_esteira.setGeometry(QtCore.QRect(30, 20, 161, 22))
        self.horizontalSlider_esteira.setMinimum(-100)
        self.horizontalSlider_esteira.setMaximum(100)
        self.horizontalSlider_esteira.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_esteira.setObjectName(_fromUtf8("horizontalSlider_esteira"))
        self.lcdNumber_esteiraVelocidade = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_esteiraVelocidade.setGeometry(QtCore.QRect(130, 50, 71, 31))
        self.lcdNumber_esteiraVelocidade.setDigitCount(3)
        self.lcdNumber_esteiraVelocidade.setObjectName(_fromUtf8("lcdNumber_esteiraVelocidade"))
        self.pushButton_esteiraParar = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_esteiraParar.setEnabled(False)
        self.pushButton_esteiraParar.setGeometry(QtCore.QRect(10, 50, 71, 32))
        self.pushButton_esteiraParar.setObjectName(_fromUtf8("pushButton_esteiraParar"))
        self.radioButton_esteiraTras = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_esteiraTras.setEnabled(False)
        self.radioButton_esteiraTras.setGeometry(QtCore.QRect(10, 20, 21, 17))
        self.radioButton_esteiraTras.setText(_fromUtf8(""))
        self.radioButton_esteiraTras.setAutoExclusive(False)
        self.radioButton_esteiraTras.setObjectName(_fromUtf8("radioButton_esteiraTras"))
        self.radioButton_esteiraFrente = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_esteiraFrente.setEnabled(False)
        self.radioButton_esteiraFrente.setGeometry(QtCore.QRect(200, 20, 21, 17))
        self.radioButton_esteiraFrente.setText(_fromUtf8(""))
        self.radioButton_esteiraFrente.setChecked(False)
        self.radioButton_esteiraFrente.setAutoExclusive(False)
        self.radioButton_esteiraFrente.setObjectName(_fromUtf8("radioButton_esteiraFrente"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 90, 221, 161))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalSlider_r06 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r06.setEnabled(False)
        self.horizontalSlider_r06.setGeometry(QtCore.QRect(150, 90, 61, 21))
        self.horizontalSlider_r06.setMaximum(100)
        self.horizontalSlider_r06.setSingleStep(1)
        self.horizontalSlider_r06.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r06.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_r06.setTickInterval(100)
        self.horizontalSlider_r06.setObjectName(_fromUtf8("horizontalSlider_r06"))
        self.horizontalSlider_r02 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r02.setEnabled(False)
        self.horizontalSlider_r02.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.horizontalSlider_r02.setMaximum(100)
        self.horizontalSlider_r02.setSingleStep(1)
        self.horizontalSlider_r02.setPageStep(1)
        self.horizontalSlider_r02.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r02.setObjectName(_fromUtf8("horizontalSlider_r02"))
        self.horizontalSlider_r03 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r03.setEnabled(False)
        self.horizontalSlider_r03.setGeometry(QtCore.QRect(80, 40, 61, 21))
        self.horizontalSlider_r03.setMaximum(100)
        self.horizontalSlider_r03.setSingleStep(1)
        self.horizontalSlider_r03.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r03.setObjectName(_fromUtf8("horizontalSlider_r03"))
        self.horizontalSlider_r01 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r01.setEnabled(False)
        self.horizontalSlider_r01.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.horizontalSlider_r01.setMaximum(100)
        self.horizontalSlider_r01.setSingleStep(1)
        self.horizontalSlider_r01.setPageStep(1)
        self.horizontalSlider_r01.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r01.setObjectName(_fromUtf8("horizontalSlider_r01"))
        self.horizontalSlider_r04 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r04.setEnabled(False)
        self.horizontalSlider_r04.setGeometry(QtCore.QRect(80, 90, 61, 21))
        self.horizontalSlider_r04.setMaximum(100)
        self.horizontalSlider_r04.setSingleStep(1)
        self.horizontalSlider_r04.setPageStep(1)
        self.horizontalSlider_r04.setProperty("value", 0)
        self.horizontalSlider_r04.setSliderPosition(0)
        self.horizontalSlider_r04.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r04.setObjectName(_fromUtf8("horizontalSlider_r04"))
        self.horizontalSlider_r05 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r05.setEnabled(False)
        self.horizontalSlider_r05.setGeometry(QtCore.QRect(150, 40, 61, 21))
        self.horizontalSlider_r05.setMaximum(100)
        self.horizontalSlider_r05.setSingleStep(1)
        self.horizontalSlider_r05.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r05.setObjectName(_fromUtf8("horizontalSlider_r05"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(170, 10, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(170, 130, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 56, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(80, 70, 56, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(150, 70, 56, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber_resistenciaControle = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_resistenciaControle.setGeometry(QtCore.QRect(10, 120, 71, 31))
        self.lcdNumber_resistenciaControle.setObjectName(_fromUtf8("lcdNumber_resistenciaControle"))
        self.radioButton_hold = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_hold.setEnabled(False)
        self.radioButton_hold.setGeometry(QtCore.QRect(100, 130, 71, 21))
        self.radioButton_hold.setObjectName(_fromUtf8("radioButton_hold"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 250, 221, 221))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_serialManual = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_serialManual.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.lineEdit_serialManual.setInputMask(_fromUtf8(""))
        self.lineEdit_serialManual.setText(_fromUtf8(""))
        self.lineEdit_serialManual.setObjectName(_fromUtf8("lineEdit_serialManual"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 50, 221, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textEdit_dadosSerial = QtGui.QTextEdit(self.tab_4)
        self.textEdit_dadosSerial.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.textEdit_dadosSerial.setFont(font)
        self.textEdit_dadosSerial.setObjectName(_fromUtf8("textEdit_dadosSerial"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.textEdit_temperatura = QtGui.QTextEdit(self.tab_5)
        self.textEdit_temperatura.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEdit_temperatura.setFont(font)
        self.textEdit_temperatura.setObjectName(_fromUtf8("textEdit_temperatura"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.pushButton_serialEnviaLinha = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_serialEnviaLinha.setEnabled(False)
        self.pushButton_serialEnviaLinha.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.pushButton_serialEnviaLinha.setObjectName(_fromUtf8("pushButton_serialEnviaLinha"))
        self.widget = matplotlibWidget(self.tab)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(230, 50, 391, 351))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.checkBox_sensor1 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor1.setGeometry(QtCore.QRect(240, 10, 85, 18))
        self.checkBox_sensor1.setChecked(True)
        self.checkBox_sensor1.setObjectName(_fromUtf8("checkBox_sensor1"))
        self.checkBox_sensor2 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor2.setGeometry(QtCore.QRect(240, 30, 85, 18))
        self.checkBox_sensor2.setChecked(True)
        self.checkBox_sensor2.setObjectName(_fromUtf8("checkBox_sensor2"))
        self.checkBox_sensor4 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor4.setGeometry(QtCore.QRect(330, 30, 85, 18))
        self.checkBox_sensor4.setChecked(True)
        self.checkBox_sensor4.setObjectName(_fromUtf8("checkBox_sensor4"))
        self.checkBox_sensor3 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor3.setGeometry(QtCore.QRect(330, 10, 85, 18))
        self.checkBox_sensor3.setChecked(True)
        self.checkBox_sensor3.setObjectName(_fromUtf8("checkBox_sensor3"))
        self.checkBox_sensor6 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor6.setGeometry(QtCore.QRect(420, 30, 85, 18))
        self.checkBox_sensor6.setChecked(True)
        self.checkBox_sensor6.setObjectName(_fromUtf8("checkBox_sensor6"))
        self.checkBox_sensor5 = QtGui.QCheckBox(self.tab)
        self.checkBox_sensor5.setGeometry(QtCore.QRect(420, 10, 85, 18))
        self.checkBox_sensor5.setChecked(True)
        self.checkBox_sensor5.setObjectName(_fromUtf8("checkBox_sensor5"))
        self.checkBox_simulacao = QtGui.QCheckBox(self.tab)
        self.checkBox_simulacao.setGeometry(QtCore.QRect(510, 10, 111, 18))
        self.checkBox_simulacao.setChecked(False)
        self.checkBox_simulacao.setObjectName(_fromUtf8("checkBox_simulacao"))
        self.checkBox_esteira = QtGui.QCheckBox(self.tab)
        self.checkBox_esteira.setGeometry(QtCore.QRect(510, 30, 85, 18))
        self.checkBox_esteira.setChecked(False)
        self.checkBox_esteira.setObjectName(_fromUtf8("checkBox_esteira"))
        self.horizontalSlider_graficoPeriodo = QtGui.QSlider(self.tab)
        self.horizontalSlider_graficoPeriodo.setGeometry(QtCore.QRect(360, 430, 151, 21))
        self.horizontalSlider_graficoPeriodo.setMinimum(1)
        self.horizontalSlider_graficoPeriodo.setMaximum(180)
        self.horizontalSlider_graficoPeriodo.setProperty("value", 60)
        self.horizontalSlider_graficoPeriodo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_graficoPeriodo.setObjectName(_fromUtf8("horizontalSlider_graficoPeriodo"))
        self.label_graficoTempo = QtGui.QLabel(self.tab)
        self.label_graficoTempo.setGeometry(QtCore.QRect(390, 410, 151, 16))
        self.label_graficoTempo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graficoTempo.setObjectName(_fromUtf8("label_graficoTempo"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(360, 450, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(440, 450, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBox_graficoAuto = QtGui.QCheckBox(self.tab)
        self.checkBox_graficoAuto.setEnabled(False)
        self.checkBox_graficoAuto.setGeometry(QtCore.QRect(320, 410, 61, 18))
        self.checkBox_graficoAuto.setChecked(False)
        self.checkBox_graficoAuto.setObjectName(_fromUtf8("checkBox_graficoAuto"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(550, 410, 61, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.spinBox_graficoLatencia = QtGui.QSpinBox(self.tab)
        self.spinBox_graficoLatencia.setGeometry(QtCore.QRect(550, 430, 61, 31))
        self.spinBox_graficoLatencia.setMinimum(1)
        self.spinBox_graficoLatencia.setSingleStep(1)
        self.spinBox_graficoLatencia.setProperty("value", 5)
        self.spinBox_graficoLatencia.setObjectName(_fromUtf8("spinBox_graficoLatencia"))
        self.pushButton_limpaTexto = QtGui.QPushButton(self.tab)
        self.pushButton_limpaTexto.setGeometry(QtCore.QRect(230, 410, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_limpaTexto.setFont(font)
        self.pushButton_limpaTexto.setObjectName(_fromUtf8("pushButton_limpaTexto"))
        self.pushButton_updateInfo = QtGui.QPushButton(self.tab)
        self.pushButton_updateInfo.setEnabled(False)
        self.pushButton_updateInfo.setGeometry(QtCore.QRect(230, 440, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_updateInfo.setFont(font)
        self.pushButton_updateInfo.setObjectName(_fromUtf8("pushButton_updateInfo"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 121, 111))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinBox_cameraRefresh = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_cameraRefresh.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.spinBox_cameraRefresh.setMinimum(1)
        self.spinBox_cameraRefresh.setMaximum(5000)
        self.spinBox_cameraRefresh.setSingleStep(1)
        self.spinBox_cameraRefresh.setProperty("value", 10)
        self.spinBox_cameraRefresh.setObjectName(_fromUtf8("spinBox_cameraRefresh"))
        self.checkBox_cameraAutoUpdate = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_cameraAutoUpdate.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.checkBox_cameraAutoUpdate.setObjectName(_fromUtf8("checkBox_cameraAutoUpdate"))
        self.checkBox_cameraAutoSave = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_cameraAutoSave.setGeometry(QtCore.QRect(0, 40, 121, 20))
        self.checkBox_cameraAutoSave.setObjectName(_fromUtf8("checkBox_cameraAutoSave"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 121, 221))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.spinBox_cameraDelay = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_cameraDelay.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.spinBox_cameraDelay.setMinimum(10)
        self.spinBox_cameraDelay.setMaximum(5000)
        self.spinBox_cameraDelay.setSingleStep(10)
        self.spinBox_cameraDelay.setProperty("value", 1000)
        self.spinBox_cameraDelay.setObjectName(_fromUtf8("spinBox_cameraDelay"))
        self.comboBox_cameraResolucao = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_cameraResolucao.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.comboBox_cameraResolucao.setObjectName(_fromUtf8("comboBox_cameraResolucao"))
        self.comboBox_cameraResolucao.addItem(_fromUtf8(""))
        self.comboBox_cameraResolucao.addItem(_fromUtf8(""))
        self.comboBox_cameraResolucao.addItem(_fromUtf8(""))
        self.comboBox_cameraResolucao.addItem(_fromUtf8(""))
        self.pushButton_tiraFoto = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_tiraFoto.setGeometry(QtCore.QRect(0, 20, 121, 61))
        self.pushButton_tiraFoto.setObjectName(_fromUtf8("pushButton_tiraFoto"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_salvaImagen = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_salvaImagen.setGeometry(QtCore.QRect(0, 180, 121, 31))
        self.pushButton_salvaImagen.setObjectName(_fromUtf8("pushButton_salvaImagen"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 360, 121, 101))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 20, 121, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_12.setGeometry(QtCore.QRect(0, 50, 121, 20))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_13.setGeometry(QtCore.QRect(0, 70, 91, 20))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.label_camera = QtGui.QLabel(self.tab_2)
        self.label_camera.setGeometry(QtCore.QRect(160, 10, 461, 346))
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName(_fromUtf8("label_camera"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.pushButton_gerarArquivo = QtGui.QPushButton(self.tab_6)
        self.pushButton_gerarArquivo.setGeometry(QtCore.QRect(10, 20, 121, 111))
        self.pushButton_gerarArquivo.setObjectName(_fromUtf8("pushButton_gerarArquivo"))
        self.pushButton_enviarEmail = QtGui.QPushButton(self.tab_6)
        self.pushButton_enviarEmail.setGeometry(QtCore.QRect(10, 150, 121, 41))
        self.pushButton_enviarEmail.setObjectName(_fromUtf8("pushButton_enviarEmail"))
        self.pushButton_pendrive = QtGui.QPushButton(self.tab_6)
        self.pushButton_pendrive.setGeometry(QtCore.QRect(10, 210, 121, 41))
        self.pushButton_pendrive.setObjectName(_fromUtf8("pushButton_pendrive"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 330, 121, 111))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.checkBox_formatoTxt = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_formatoTxt.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_formatoTxt.setChecked(True)
        self.checkBox_formatoTxt.setAutoExclusive(True)
        self.checkBox_formatoTxt.setObjectName(_fromUtf8("checkBox_formatoTxt"))
        self.checkBox_formatoCsv = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_formatoCsv.setGeometry(QtCore.QRect(10, 70, 81, 17))
        self.checkBox_formatoCsv.setAutoExclusive(True)
        self.checkBox_formatoCsv.setObjectName(_fromUtf8("checkBox_formatoCsv"))
        self.pushButton_zerarBanco = QtGui.QPushButton(self.tab_6)
        self.pushButton_zerarBanco.setGeometry(QtCore.QRect(10, 270, 121, 41))
        self.pushButton_zerarBanco.setObjectName(_fromUtf8("pushButton_zerarBanco"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_11.setGeometry(QtCore.QRect(160, 300, 231, 141))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.lineEdit_email = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_email.setGeometry(QtCore.QRect(10, 30, 211, 21))
        self.lineEdit_email.setInputMask(_fromUtf8(""))
        self.lineEdit_email.setObjectName(_fromUtf8("lineEdit_email"))
        self.lineEdit_senha = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_senha.setGeometry(QtCore.QRect(10, 70, 211, 21))
        self.lineEdit_senha.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_senha.setReadOnly(False)
        self.lineEdit_senha.setObjectName(_fromUtf8("lineEdit_senha"))
        self.pushButton_limpaSenha = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_limpaSenha.setGeometry(QtCore.QRect(10, 110, 211, 23))
        self.pushButton_limpaSenha.setObjectName(_fromUtf8("pushButton_limpaSenha"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_12.setGeometry(QtCore.QRect(160, 140, 231, 91))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.checkBox_experimentoPeriodo = QtGui.QCheckBox(self.groupBox_12)
        self.checkBox_experimentoPeriodo.setGeometry(QtCore.QRect(10, 50, 61, 17))
        self.checkBox_experimentoPeriodo.setChecked(True)
        self.checkBox_experimentoPeriodo.setAutoExclusive(True)
        self.checkBox_experimentoPeriodo.setObjectName(_fromUtf8("checkBox_experimentoPeriodo"))
        self.checkBox_experimentoAtualData = QtGui.QCheckBox(self.groupBox_12)
        self.checkBox_experimentoAtualData.setEnabled(False)
        self.checkBox_experimentoAtualData.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.checkBox_experimentoAtualData.setChecked(False)
        self.checkBox_experimentoAtualData.setAutoExclusive(True)
        self.checkBox_experimentoAtualData.setObjectName(_fromUtf8("checkBox_experimentoAtualData"))
        self.dateTimeEdit_inicio = QtGui.QDateTimeEdit(self.groupBox_12)
        self.dateTimeEdit_inicio.setGeometry(QtCore.QRect(80, 20, 141, 22))
        self.dateTimeEdit_inicio.setCalendarPopup(True)
        self.dateTimeEdit_inicio.setObjectName(_fromUtf8("dateTimeEdit_inicio"))
        self.dateTimeEdit_fim = QtGui.QDateTimeEdit(self.groupBox_12)
        self.dateTimeEdit_fim.setGeometry(QtCore.QRect(80, 50, 141, 22))
        self.dateTimeEdit_fim.setCalendarPopup(True)
        self.dateTimeEdit_fim.setObjectName(_fromUtf8("dateTimeEdit_fim"))
        self.label_19 = QtGui.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(170, 20, 101, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_nomeExperimento = QtGui.QLabel(self.tab_6)
        self.label_nomeExperimento.setGeometry(QtCore.QRect(280, 20, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nomeExperimento.setFont(font)
        self.label_nomeExperimento.setObjectName(_fromUtf8("label_nomeExperimento"))
        self.pushButton_experimento = QtGui.QPushButton(self.tab_6)
        self.pushButton_experimento.setGeometry(QtCore.QRect(160, 60, 231, 71))
        self.pushButton_experimento.setObjectName(_fromUtf8("pushButton_experimento"))
        self.pushButton_localArquivo = QtGui.QPushButton(self.tab_6)
        self.pushButton_localArquivo.setGeometry(QtCore.QRect(220, 240, 121, 23))
        self.pushButton_localArquivo.setObjectName(_fromUtf8("pushButton_localArquivo"))
        self.label_caminho = QtGui.QLabel(self.tab_6)
        self.label_caminho.setGeometry(QtCore.QRect(170, 270, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_caminho.setFont(font)
        self.label_caminho.setText(_fromUtf8(""))
        self.label_caminho.setAlignment(QtCore.Qt.AlignCenter)
        self.label_caminho.setObjectName(_fromUtf8("label_caminho"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setGeometry(QtCore.QRect(400, 20, 231, 431))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.label_17 = QtGui.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_21 = QtGui.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_S01A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S01A.setGeometry(QtCore.QRect(60, 50, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S01A.setFont(font)
        self.lineEdit_S01A.setText(_fromUtf8(""))
        self.lineEdit_S01A.setObjectName(_fromUtf8("lineEdit_S01A"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_S01B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S01B.setGeometry(QtCore.QRect(160, 50, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S01B.setFont(font)
        self.lineEdit_S01B.setText(_fromUtf8(""))
        self.lineEdit_S01B.setObjectName(_fromUtf8("lineEdit_S01B"))
        self.lineEdit_S02B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S02B.setGeometry(QtCore.QRect(160, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S02B.setFont(font)
        self.lineEdit_S02B.setText(_fromUtf8(""))
        self.lineEdit_S02B.setObjectName(_fromUtf8("lineEdit_S02B"))
        self.lineEdit_S02A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S02A.setGeometry(QtCore.QRect(60, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S02A.setFont(font)
        self.lineEdit_S02A.setText(_fromUtf8(""))
        self.lineEdit_S02A.setObjectName(_fromUtf8("lineEdit_S02A"))
        self.label_23 = QtGui.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(130, 100, 21, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_S03B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S03B.setGeometry(QtCore.QRect(160, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S03B.setFont(font)
        self.lineEdit_S03B.setText(_fromUtf8(""))
        self.lineEdit_S03B.setObjectName(_fromUtf8("lineEdit_S03B"))
        self.lineEdit_S03A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S03A.setGeometry(QtCore.QRect(60, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S03A.setFont(font)
        self.lineEdit_S03A.setText(_fromUtf8(""))
        self.lineEdit_S03A.setObjectName(_fromUtf8("lineEdit_S03A"))
        self.label_25 = QtGui.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(130, 150, 21, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_S04B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S04B.setGeometry(QtCore.QRect(160, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S04B.setFont(font)
        self.lineEdit_S04B.setText(_fromUtf8(""))
        self.lineEdit_S04B.setObjectName(_fromUtf8("lineEdit_S04B"))
        self.lineEdit_S04A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S04A.setGeometry(QtCore.QRect(60, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S04A.setFont(font)
        self.lineEdit_S04A.setText(_fromUtf8(""))
        self.lineEdit_S04A.setObjectName(_fromUtf8("lineEdit_S04A"))
        self.label_27 = QtGui.QLabel(self.tab_7)
        self.label_27.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_7)
        self.label_28.setGeometry(QtCore.QRect(130, 200, 21, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_S05B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S05B.setGeometry(QtCore.QRect(160, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S05B.setFont(font)
        self.lineEdit_S05B.setText(_fromUtf8(""))
        self.lineEdit_S05B.setObjectName(_fromUtf8("lineEdit_S05B"))
        self.lineEdit_S05A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S05A.setGeometry(QtCore.QRect(60, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S05A.setFont(font)
        self.lineEdit_S05A.setText(_fromUtf8(""))
        self.lineEdit_S05A.setObjectName(_fromUtf8("lineEdit_S05A"))
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 250, 51, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_7)
        self.label_30.setGeometry(QtCore.QRect(130, 250, 21, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lineEdit_S06B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S06B.setGeometry(QtCore.QRect(160, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S06B.setFont(font)
        self.lineEdit_S06B.setText(_fromUtf8(""))
        self.lineEdit_S06B.setObjectName(_fromUtf8("lineEdit_S06B"))
        self.lineEdit_S06A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S06A.setGeometry(QtCore.QRect(60, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S06A.setFont(font)
        self.lineEdit_S06A.setText(_fromUtf8(""))
        self.lineEdit_S06A.setObjectName(_fromUtf8("lineEdit_S06A"))
        self.label_31 = QtGui.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(10, 300, 51, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_7)
        self.label_32.setGeometry(QtCore.QRect(130, 300, 21, 21))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.pushButton_salvarFit = QtGui.QPushButton(self.tab_7)
        self.pushButton_salvarFit.setGeometry(QtCore.QRect(10, 360, 111, 31))
        self.pushButton_salvarFit.setObjectName(_fromUtf8("pushButton_salvarFit"))
        self.comboBox_fitLinear = QtGui.QComboBox(self.tab_7)
        self.comboBox_fitLinear.setGeometry(QtCore.QRect(10, 330, 211, 31))
        self.comboBox_fitLinear.setObjectName(_fromUtf8("comboBox_fitLinear"))
        self.pushButton_deletarFit = QtGui.QPushButton(self.tab_7)
        self.pushButton_deletarFit.setGeometry(QtCore.QRect(120, 360, 101, 31))
        self.pushButton_deletarFit.setObjectName(_fromUtf8("pushButton_deletarFit"))
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(660, 0, 131, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_conectar = QtGui.QPushButton(self.groupBox)
        self.pushButton_conectar.setGeometry(QtCore.QRect(0, 20, 131, 31))
        self.pushButton_conectar.setObjectName(_fromUtf8("pushButton_conectar"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 50, 131, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 131, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_portaSerial = QtGui.QComboBox(self.groupBox)
        self.comboBox_portaSerial.setGeometry(QtCore.QRect(0, 70, 131, 26))
        self.comboBox_portaSerial.setObjectName(_fromUtf8("comboBox_portaSerial"))
        self.comboBox_baudRate = QtGui.QComboBox(self.groupBox)
        self.comboBox_baudRate.setGeometry(QtCore.QRect(0, 120, 131, 26))
        self.comboBox_baudRate.setObjectName(_fromUtf8("comboBox_baudRate"))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.comboBox_baudRate.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 150, 131, 421))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lcdNumber_s1 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s1.setGeometry(QtCore.QRect(10, 30, 111, 41))
        self.lcdNumber_s1.setSmallDecimalPoint(True)
        self.lcdNumber_s1.setProperty("value", 23.0)
        self.lcdNumber_s1.setObjectName(_fromUtf8("lcdNumber_s1"))
        self.lcdNumber_s2 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s2.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.lcdNumber_s2.setSmallDecimalPoint(True)
        self.lcdNumber_s2.setProperty("value", 23.0)
        self.lcdNumber_s2.setObjectName(_fromUtf8("lcdNumber_s2"))
        self.lcdNumber_s4 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s4.setGeometry(QtCore.QRect(10, 180, 111, 41))
        self.lcdNumber_s4.setSmallDecimalPoint(True)
        self.lcdNumber_s4.setProperty("value", 23.0)
        self.lcdNumber_s4.setObjectName(_fromUtf8("lcdNumber_s4"))
        self.lcdNumber_s6 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s6.setGeometry(QtCore.QRect(10, 280, 111, 41))
        self.lcdNumber_s6.setSmallDecimalPoint(True)
        self.lcdNumber_s6.setProperty("value", 23.0)
        self.lcdNumber_s6.setObjectName(_fromUtf8("lcdNumber_s6"))
        self.pushButton_serialAtualiza = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_serialAtualiza.setEnabled(False)
        self.pushButton_serialAtualiza.setGeometry(QtCore.QRect(10, 330, 111, 31))
        self.pushButton_serialAtualiza.setObjectName(_fromUtf8("pushButton_serialAtualiza"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 390, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.spinBox_serialUpdate = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_serialUpdate.setGeometry(QtCore.QRect(70, 370, 53, 31))
        self.spinBox_serialUpdate.setMinimum(1)
        self.spinBox_serialUpdate.setSingleStep(1)
        self.spinBox_serialUpdate.setProperty("value", 5)
        self.spinBox_serialUpdate.setObjectName(_fromUtf8("spinBox_serialUpdate"))
        self.checkBox_serialAuto = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_serialAuto.setEnabled(False)
        self.checkBox_serialAuto.setGeometry(QtCore.QRect(10, 370, 51, 18))
        self.checkBox_serialAuto.setChecked(False)
        self.checkBox_serialAuto.setObjectName(_fromUtf8("checkBox_serialAuto"))
        self.lcdNumber_s5 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s5.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.lcdNumber_s5.setSmallDecimalPoint(True)
        self.lcdNumber_s5.setProperty("value", 23.0)
        self.lcdNumber_s5.setObjectName(_fromUtf8("lcdNumber_s5"))
        self.lcdNumber_s3 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_s3.setGeometry(QtCore.QRect(10, 130, 111, 41))
        self.lcdNumber_s3.setSmallDecimalPoint(True)
        self.lcdNumber_s3.setProperty("value", 23.0)
        self.lcdNumber_s3.setObjectName(_fromUtf8("lcdNumber_s3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 500, 411, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.progressBar_r05 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r05.setGeometry(QtCore.QRect(290, 20, 118, 23))
        self.progressBar_r05.setProperty("value", 0)
        self.progressBar_r05.setObjectName(_fromUtf8("progressBar_r05"))
        self.progressBar_r01 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r01.setGeometry(QtCore.QRect(10, 20, 118, 23))
        self.progressBar_r01.setProperty("value", 0)
        self.progressBar_r01.setObjectName(_fromUtf8("progressBar_r01"))
        self.progressBar_r02 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r02.setGeometry(QtCore.QRect(10, 40, 118, 23))
        self.progressBar_r02.setProperty("value", 0)
        self.progressBar_r02.setObjectName(_fromUtf8("progressBar_r02"))
        self.progressBar_r06 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r06.setGeometry(QtCore.QRect(290, 40, 118, 23))
        self.progressBar_r06.setProperty("value", 0)
        self.progressBar_r06.setObjectName(_fromUtf8("progressBar_r06"))
        self.progressBar_r04 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r04.setGeometry(QtCore.QRect(150, 40, 118, 23))
        self.progressBar_r04.setProperty("value", 0)
        self.progressBar_r04.setObjectName(_fromUtf8("progressBar_r04"))
        self.progressBar_r03 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r03.setGeometry(QtCore.QRect(150, 20, 118, 23))
        self.progressBar_r03.setProperty("value", 0)
        self.progressBar_r03.setObjectName(_fromUtf8("progressBar_r03"))
        self.pushButton_emergencia = QtGui.QPushButton(self.centralwidget)
        self.pushButton_emergencia.setEnabled(False)
        self.pushButton_emergencia.setGeometry(QtCore.QRect(10, 510, 221, 61))
        self.pushButton_emergencia.setStyleSheet(_fromUtf8("background-color: red"))
        self.pushButton_emergencia.setObjectName(_fromUtf8("pushButton_emergencia"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTeste2 = QtGui.QAction(MainWindow)
        self.actionTeste2.setObjectName(_fromUtf8("actionTeste2"))
        self.actionParte1 = QtGui.QAction(MainWindow)
        self.actionParte1.setCheckable(False)
        self.actionParte1.setObjectName(_fromUtf8("actionParte1"))
        self.actionParte2 = QtGui.QAction(MainWindow)
        self.actionParte2.setCheckable(False)
        self.actionParte2.setChecked(False)
        self.actionParte2.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionParte2.setObjectName(_fromUtf8("actionParte2"))
        self.actionCOM1 = QtGui.QAction(MainWindow)
        self.actionCOM1.setCheckable(True)
        self.actionCOM1.setObjectName(_fromUtf8("actionCOM1"))
        self.actionCOM2 = QtGui.QAction(MainWindow)
        self.actionCOM2.setCheckable(True)
        self.actionCOM2.setObjectName(_fromUtf8("actionCOM2"))
        self.actionCOM3 = QtGui.QAction(MainWindow)
        self.actionCOM3.setCheckable(True)
        self.actionCOM3.setObjectName(_fromUtf8("actionCOM3"))
        self.action_dev_ttyA0 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA0.setCheckable(True)
        self.action_dev_ttyA0.setChecked(True)
        self.action_dev_ttyA0.setObjectName(_fromUtf8("action_dev_ttyA0"))
        self.action_dev_ttyA1 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA1.setCheckable(True)
        self.action_dev_ttyA1.setObjectName(_fromUtf8("action_dev_ttyA1"))
        self.action9600 = QtGui.QAction(MainWindow)
        self.action9600.setCheckable(True)
        self.action9600.setChecked(True)
        self.action9600.setObjectName(_fromUtf8("action9600"))
        self.actionImportar_dados = QtGui.QAction(MainWindow)
        self.actionImportar_dados.setObjectName(_fromUtf8("actionImportar_dados"))
        self.actionEnviar_Arquivos = QtGui.QAction(MainWindow)
        self.actionEnviar_Arquivos.setObjectName(_fromUtf8("actionEnviar_Arquivos"))
        self.actionVideo = QtGui.QAction(MainWindow)
        self.actionVideo.setObjectName(_fromUtf8("actionVideo"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.action11500 = QtGui.QAction(MainWindow)
        self.action11500.setCheckable(True)
        self.action11500.setObjectName(_fromUtf8("action11500"))
        self.actionExportar_como_csv = QtGui.QAction(MainWindow)
        self.actionExportar_como_csv.setObjectName(_fromUtf8("actionExportar_como_csv"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXLS = QtGui.QAction(MainWindow)
        self.actionXLS.setObjectName(_fromUtf8("actionXLS"))
        self.actionTXT = QtGui.QAction(MainWindow)
        self.actionTXT.setObjectName(_fromUtf8("actionTXT"))
        self.actionNumpy = QtGui.QAction(MainWindow)
        self.actionNumpy.setObjectName(_fromUtf8("actionNumpy"))
        self.action0_5s = QtGui.QAction(MainWindow)
        self.action0_5s.setCheckable(True)
        self.action0_5s.setObjectName(_fromUtf8("action0_5s"))
        self.action1s = QtGui.QAction(MainWindow)
        self.action1s.setCheckable(True)
        self.action1s.setObjectName(_fromUtf8("action1s"))
        self.action1_5s = QtGui.QAction(MainWindow)
        self.action1_5s.setCheckable(True)
        self.action1_5s.setObjectName(_fromUtf8("action1_5s"))
        self.action2s = QtGui.QAction(MainWindow)
        self.action2s.setCheckable(True)
        self.action2s.setChecked(True)
        self.action2s.setObjectName(_fromUtf8("action2s"))
        self.action3s = QtGui.QAction(MainWindow)
        self.action3s.setCheckable(True)
        self.action3s.setObjectName(_fromUtf8("action3s"))
        self.action5s = QtGui.QAction(MainWindow)
        self.action5s.setCheckable(True)
        self.action5s.setObjectName(_fromUtf8("action5s"))
        self.action10s = QtGui.QAction(MainWindow)
        self.action10s.setCheckable(True)
        self.action10s.setObjectName(_fromUtf8("action10s"))
        self.actionCustom = QtGui.QAction(MainWindow)
        self.actionCustom.setObjectName(_fromUtf8("actionCustom"))
        self.actionResolu_o_1 = QtGui.QAction(MainWindow)
        self.actionResolu_o_1.setObjectName(_fromUtf8("actionResolu_o_1"))
        self.actionResolu_o_2 = QtGui.QAction(MainWindow)
        self.actionResolu_o_2.setObjectName(_fromUtf8("actionResolu_o_2"))
        self.actionExclusive = QtGui.QAction(MainWindow)
        self.actionExclusive.setObjectName(_fromUtf8("actionExclusive"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox_cameraResolucao.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(0)
        self.comboBox_baudRate.setCurrentIndex(1)
        QtCore.QObject.connect(self.horizontalSlider_esteira, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_esteiraVelocidade.display)
        QtCore.QObject.connect(self.horizontalSlider_r02, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QObject.connect(self.horizontalSlider_r04, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QObject.connect(self.horizontalSlider_r06, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QObject.connect(self.horizontalSlider_r05, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QObject.connect(self.horizontalSlider_r03, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QObject.connect(self.horizontalSlider_r01, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_resistenciaControle.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Esteira", None))
        self.pushButton_esteiraParar.setText(_translate("MainWindow", "Parar", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Resistências", None))
        self.label_4.setText(_translate("MainWindow", "Superior", None))
        self.label_5.setText(_translate("MainWindow", "Inferior", None))
        self.label_6.setText(_translate("MainWindow", "Esquerda", None))
        self.label_7.setText(_translate("MainWindow", "Centro", None))
        self.label_8.setText(_translate("MainWindow", "Direita", None))
        self.radioButton_hold.setText(_translate("MainWindow", "Hold", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Comando Manual", None))
        self.lineEdit_serialManual.setPlaceholderText(_translate("MainWindow", "Comandos Manuais", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Dados Serial", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Temperatura", None))
        self.pushButton_serialEnviaLinha.setText(_translate("MainWindow", "Envia", None))
        self.checkBox_sensor1.setText(_translate("MainWindow", "Sensor 1", None))
        self.checkBox_sensor2.setText(_translate("MainWindow", "Sensor 2", None))
        self.checkBox_sensor4.setText(_translate("MainWindow", "Sensor 4", None))
        self.checkBox_sensor3.setText(_translate("MainWindow", "Sensor 3", None))
        self.checkBox_sensor6.setText(_translate("MainWindow", "Sensor 6", None))
        self.checkBox_sensor5.setText(_translate("MainWindow", "Sensor 5", None))
        self.checkBox_simulacao.setText(_translate("MainWindow", "Simulação", None))
        self.checkBox_esteira.setText(_translate("MainWindow", "Esteira", None))
        self.label_graficoTempo.setText(_translate("MainWindow", "Delta T = 60min", None))
        self.label_10.setText(_translate("MainWindow", "1 min", None))
        self.label_11.setText(_translate("MainWindow", "180 min", None))
        self.checkBox_graficoAuto.setText(_translate("MainWindow", "Auto", None))
        self.label_16.setText(_translate("MainWindow", "Latência:", None))
        self.pushButton_limpaTexto.setText(_translate("MainWindow", "LimparTexto", None))
        self.pushButton_updateInfo.setText(_translate("MainWindow", "Update Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Manual", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Automatico", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Automatico", None))
        self.label_14.setText(_translate("MainWindow", "Refresh (s)", None))
        self.checkBox_cameraAutoUpdate.setText(_translate("MainWindow", "Auto update", None))
        self.checkBox_cameraAutoSave.setText(_translate("MainWindow", "Auto Save", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Manual - Imagem", None))
        self.comboBox_cameraResolucao.setItemText(0, _translate("MainWindow", "2592x1944", None))
        self.comboBox_cameraResolucao.setItemText(1, _translate("MainWindow", "1296x972", None))
        self.comboBox_cameraResolucao.setItemText(2, _translate("MainWindow", "1296x730", None))
        self.comboBox_cameraResolucao.setItemText(3, _translate("MainWindow", "640x480", None))
        self.pushButton_tiraFoto.setText(_translate("MainWindow", "Tira Foto", None))
        self.label_13.setText(_translate("MainWindow", "Delay (ms)", None))
        self.label_12.setText(_translate("MainWindow", "Resolução", None))
        self.pushButton_salvaImagen.setText(_translate("MainWindow", "Salva Imagem", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "AutoDetecção", None))
        self.pushButton_10.setText(_translate("MainWindow", "Configurações", None))
        self.checkBox_12.setText(_translate("MainWindow", "Auto Detect", None))
        self.checkBox_13.setText(_translate("MainWindow", "Alerta", None))
        self.label_camera.setText(_translate("MainWindow", "PI Camera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Camera", None))
        self.pushButton_gerarArquivo.setText(_translate("MainWindow", "Gerar Arquivo", None))
        self.pushButton_enviarEmail.setText(_translate("MainWindow", "Enviar e-mail", None))
        self.pushButton_pendrive.setText(_translate("MainWindow", "Pendrive", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Formato", None))
        self.checkBox_formatoTxt.setText(_translate("MainWindow", ".txt", None))
        self.checkBox_formatoCsv.setText(_translate("MainWindow", ".csv (excel)", None))
        self.pushButton_zerarBanco.setText(_translate("MainWindow", "Zerar Banco", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "E-mail  -  (gmail)", None))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "e-mail@gmail.com", None))
        self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "Senha", None))
        self.pushButton_limpaSenha.setText(_translate("MainWindow", "Limpar senha e e-mail", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Experimento", None))
        self.checkBox_experimentoPeriodo.setText(_translate("MainWindow", "periodo", None))
        self.checkBox_experimentoAtualData.setText(_translate("MainWindow", "Atual", None))
        self.label_19.setText(_translate("MainWindow", "Exp Atual:", None))
        self.label_nomeExperimento.setText(_translate("MainWindow", "Sem Nome", None))
        self.pushButton_experimento.setText(_translate("MainWindow", "Novo Experimento", None))
        self.pushButton_localArquivo.setText(_translate("MainWindow", "Local do Arquivo", None))
        self.label_17.setText(_translate("MainWindow", "T( d ) =  A  +  B *  d", None))
        self.label_21.setText(_translate("MainWindow", "S1: A =", None))
        self.label_22.setText(_translate("MainWindow", "B =", None))
        self.label_23.setText(_translate("MainWindow", "S2: A =", None))
        self.label_24.setText(_translate("MainWindow", "B =", None))
        self.label_25.setText(_translate("MainWindow", "S3: A =", None))
        self.label_26.setText(_translate("MainWindow", "B =", None))
        self.label_27.setText(_translate("MainWindow", "S4: A =", None))
        self.label_28.setText(_translate("MainWindow", "B =", None))
        self.label_29.setText(_translate("MainWindow", "S5: A =", None))
        self.label_30.setText(_translate("MainWindow", "B =", None))
        self.label_31.setText(_translate("MainWindow", "S6: A =", None))
        self.label_32.setText(_translate("MainWindow", "B =", None))
        self.pushButton_salvarFit.setText(_translate("MainWindow", "Salvar", None))
        self.pushButton_deletarFit.setText(_translate("MainWindow", "deletar", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Linear", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Polinomial", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Dados", None))
        self.groupBox.setTitle(_translate("MainWindow", "Conexão", None))
        self.pushButton_conectar.setText(_translate("MainWindow", "Conectar", None))
        self.label.setText(_translate("MainWindow", "Porta:", None))
        self.label_2.setText(_translate("MainWindow", "BaudRate", None))
        self.comboBox_baudRate.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_baudRate.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_baudRate.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_baudRate.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_baudRate.setItemText(4, _translate("MainWindow", "57600", None))
        self.comboBox_baudRate.setItemText(5, _translate("MainWindow", "115200", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sensores", None))
        self.pushButton_serialAtualiza.setText(_translate("MainWindow", "Atualiza", None))
        self.label_3.setText(_translate("MainWindow", "Latência:", None))
        self.checkBox_serialAuto.setText(_translate("MainWindow", "Auto", None))
        self.groupBox_3.setTitle(_translate("MainWindow", " Esquerda                            Potencia Resistências                           Direita", None))
        self.pushButton_emergencia.setText(_translate("MainWindow", "Emergência", None))
        self.actionTeste2.setText(_translate("MainWindow", "Imprimir", None))
        self.actionParte1.setText(_translate("MainWindow", "Salvar Configuração", None))
        self.actionParte2.setText(_translate("MainWindow", "Restaurar Padrão", None))
        self.actionCOM1.setText(_translate("MainWindow", "COM1", None))
        self.actionCOM2.setText(_translate("MainWindow", "COM2", None))
        self.actionCOM3.setText(_translate("MainWindow", "COM3", None))
        self.action_dev_ttyA0.setText(_translate("MainWindow", "/dev/ttyA0", None))
        self.action_dev_ttyA1.setText(_translate("MainWindow", "/dev/ttyA1", None))
        self.action9600.setText(_translate("MainWindow", "9600", None))
        self.actionImportar_dados.setText(_translate("MainWindow", "Importar dados", None))
        self.actionEnviar_Arquivos.setText(_translate("MainWindow", "Enviar Arquivos", None))
        self.actionVideo.setText(_translate("MainWindow", "Video", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.action11500.setText(_translate("MainWindow", "11500", None))
        self.actionExportar_como_csv.setText(_translate("MainWindow", "Exportar como csv", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionXLS.setText(_translate("MainWindow", "XLS", None))
        self.actionTXT.setText(_translate("MainWindow", "TXT", None))
        self.actionNumpy.setText(_translate("MainWindow", "Numpy", None))
        self.action0_5s.setText(_translate("MainWindow", "0.5s", None))
        self.action1s.setText(_translate("MainWindow", "1s", None))
        self.action1_5s.setText(_translate("MainWindow", "1.5s", None))
        self.action2s.setText(_translate("MainWindow", "2s", None))
        self.action3s.setText(_translate("MainWindow", "3s", None))
        self.action5s.setText(_translate("MainWindow", "5s", None))
        self.action10s.setText(_translate("MainWindow", "10s", None))
        self.actionCustom.setText(_translate("MainWindow", "Outro ...", None))
        self.actionResolu_o_1.setText(_translate("MainWindow", "Resolução 1", None))
        self.actionResolu_o_2.setText(_translate("MainWindow", "Resolução 2", None))
        self.actionExclusive.setText(_translate("MainWindow", "exclusive", None))

from matplotlibwidgetFile import matplotlibWidget
