# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/forno_design.ui'
#
# Created: Fri Sep  9 20:05:56 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(801, 617)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 641, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 201, 22))
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_7.setGeometry(QtCore.QRect(130, 50, 71, 31))
        self.lcdNumber_7.setDigitCount(3)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 50, 71, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 90, 221, 161))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalSlider_r06 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r06.setEnabled(False)
        self.horizontalSlider_r06.setGeometry(QtCore.QRect(150, 90, 61, 21))
        self.horizontalSlider_r06.setMaximum(100)
        self.horizontalSlider_r06.setSingleStep(1)
        self.horizontalSlider_r06.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r06.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_r06.setTickInterval(100)
        self.horizontalSlider_r06.setObjectName(_fromUtf8("horizontalSlider_r06"))
        self.horizontalSlider_r02 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r02.setEnabled(False)
        self.horizontalSlider_r02.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.horizontalSlider_r02.setMaximum(100)
        self.horizontalSlider_r02.setSingleStep(1)
        self.horizontalSlider_r02.setPageStep(1)
        self.horizontalSlider_r02.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r02.setObjectName(_fromUtf8("horizontalSlider_r02"))
        self.horizontalSlider_r03 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r03.setEnabled(False)
        self.horizontalSlider_r03.setGeometry(QtCore.QRect(80, 40, 61, 21))
        self.horizontalSlider_r03.setMaximum(100)
        self.horizontalSlider_r03.setSingleStep(1)
        self.horizontalSlider_r03.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r03.setObjectName(_fromUtf8("horizontalSlider_r03"))
        self.horizontalSlider_r01 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r01.setEnabled(False)
        self.horizontalSlider_r01.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.horizontalSlider_r01.setMaximum(100)
        self.horizontalSlider_r01.setSingleStep(1)
        self.horizontalSlider_r01.setPageStep(1)
        self.horizontalSlider_r01.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r01.setObjectName(_fromUtf8("horizontalSlider_r01"))
        self.horizontalSlider_r04 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r04.setEnabled(False)
        self.horizontalSlider_r04.setGeometry(QtCore.QRect(80, 90, 61, 21))
        self.horizontalSlider_r04.setMaximum(100)
        self.horizontalSlider_r04.setSingleStep(1)
        self.horizontalSlider_r04.setPageStep(1)
        self.horizontalSlider_r04.setProperty("value", 0)
        self.horizontalSlider_r04.setSliderPosition(0)
        self.horizontalSlider_r04.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r04.setObjectName(_fromUtf8("horizontalSlider_r04"))
        self.horizontalSlider_r05 = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_r05.setEnabled(False)
        self.horizontalSlider_r05.setGeometry(QtCore.QRect(150, 40, 61, 21))
        self.horizontalSlider_r05.setMaximum(100)
        self.horizontalSlider_r05.setSingleStep(1)
        self.horizontalSlider_r05.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r05.setObjectName(_fromUtf8("horizontalSlider_r05"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(160, 130, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 56, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(80, 70, 56, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(150, 70, 56, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber_8 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_8.setGeometry(QtCore.QRect(10, 120, 71, 31))
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(90, 130, 71, 21))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 250, 221, 221))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 50, 221, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textEdit = QtGui.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(9)
        font.setItalic(True)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 211, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.widget = matplotlibWidget(self.tab)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(230, 50, 391, 351))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(240, 10, 85, 18))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(240, 30, 85, 18))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 30, 85, 18))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(330, 10, 85, 18))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(420, 30, 85, 18))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(420, 10, 85, 18))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_8 = QtGui.QCheckBox(self.tab)
        self.checkBox_8.setGeometry(QtCore.QRect(510, 10, 111, 18))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_7 = QtGui.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(510, 30, 85, 18))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.horizontalSlider_8 = QtGui.QSlider(self.tab)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(360, 430, 151, 21))
        self.horizontalSlider_8.setMinimum(1)
        self.horizontalSlider_8.setMaximum(180)
        self.horizontalSlider_8.setProperty("value", 60)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(360, 410, 151, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(360, 450, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(440, 450, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBox_14 = QtGui.QCheckBox(self.tab)
        self.checkBox_14.setEnabled(True)
        self.checkBox_14.setGeometry(QtCore.QRect(510, 410, 61, 18))
        self.checkBox_14.setChecked(False)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(520, 440, 61, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.spinBox_4 = QtGui.QSpinBox(self.tab)
        self.spinBox_4.setGeometry(QtCore.QRect(580, 440, 53, 21))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setSingleStep(1)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 440, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.checkBox_20 = QtGui.QCheckBox(self.tab)
        self.checkBox_20.setEnabled(False)
        self.checkBox_20.setGeometry(QtCore.QRect(230, 410, 131, 18))
        self.checkBox_20.setChecked(False)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.pushButton_18 = QtGui.QPushButton(self.tab)
        self.pushButton_18.setGeometry(QtCore.QRect(570, 400, 61, 32))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 121, 111))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(5000)
        self.spinBox_3.setSingleStep(1)
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_10.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_11.setGeometry(QtCore.QRect(0, 40, 121, 20))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 121, 221))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.spinBox_2.setMinimum(10)
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setProperty("value", 1000)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 20, 121, 61))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 180, 121, 31))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 360, 121, 101))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 20, 121, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_12.setGeometry(QtCore.QRect(0, 50, 121, 20))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_13.setGeometry(QtCore.QRect(0, 70, 91, 20))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(160, 10, 461, 346))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 20, 121, 111))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 150, 121, 41))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.tab_6)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 210, 121, 41))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 330, 121, 111))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setAutoExclusive(True)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 70, 81, 17))
        self.checkBox_16.setAutoExclusive(True)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_6)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 270, 121, 41))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_11.setGeometry(QtCore.QRect(160, 300, 231, 141))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 211, 21))
        self.lineEdit_2.setInputMask(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 211, 21))
        self.lineEdit_3.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 110, 211, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_12.setGeometry(QtCore.QRect(160, 140, 231, 91))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox_12)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 50, 61, 17))
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setAutoExclusive(True)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox_12)
        self.checkBox_19.setEnabled(False)
        self.checkBox_19.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.checkBox_19.setChecked(False)
        self.checkBox_19.setAutoExclusive(True)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.groupBox_12)
        self.dateTimeEdit.setGeometry(QtCore.QRect(80, 20, 141, 22))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.groupBox_12)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(80, 50, 141, 22))
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.label_19 = QtGui.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(170, 20, 101, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(280, 20, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pushButton_15 = QtGui.QPushButton(self.tab_6)
        self.pushButton_15.setGeometry(QtCore.QRect(160, 60, 231, 71))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.tab_6)
        self.pushButton_16.setGeometry(QtCore.QRect(220, 240, 121, 23))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.label_18 = QtGui.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(170, 270, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_18.setFont(font)
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setGeometry(QtCore.QRect(400, 20, 231, 431))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.label_17 = QtGui.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_21 = QtGui.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_S01A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S01A.setGeometry(QtCore.QRect(60, 50, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S01A.setFont(font)
        self.lineEdit_S01A.setText(_fromUtf8(""))
        self.lineEdit_S01A.setObjectName(_fromUtf8("lineEdit_S01A"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_S01B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S01B.setGeometry(QtCore.QRect(160, 50, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S01B.setFont(font)
        self.lineEdit_S01B.setText(_fromUtf8(""))
        self.lineEdit_S01B.setObjectName(_fromUtf8("lineEdit_S01B"))
        self.lineEdit_S02B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S02B.setGeometry(QtCore.QRect(160, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S02B.setFont(font)
        self.lineEdit_S02B.setText(_fromUtf8(""))
        self.lineEdit_S02B.setObjectName(_fromUtf8("lineEdit_S02B"))
        self.lineEdit_S02A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S02A.setGeometry(QtCore.QRect(60, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S02A.setFont(font)
        self.lineEdit_S02A.setText(_fromUtf8(""))
        self.lineEdit_S02A.setObjectName(_fromUtf8("lineEdit_S02A"))
        self.label_23 = QtGui.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(130, 100, 21, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_S03B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S03B.setGeometry(QtCore.QRect(160, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S03B.setFont(font)
        self.lineEdit_S03B.setText(_fromUtf8(""))
        self.lineEdit_S03B.setObjectName(_fromUtf8("lineEdit_S03B"))
        self.lineEdit_S03A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S03A.setGeometry(QtCore.QRect(60, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S03A.setFont(font)
        self.lineEdit_S03A.setText(_fromUtf8(""))
        self.lineEdit_S03A.setObjectName(_fromUtf8("lineEdit_S03A"))
        self.label_25 = QtGui.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(130, 150, 21, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_S04B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S04B.setGeometry(QtCore.QRect(160, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S04B.setFont(font)
        self.lineEdit_S04B.setText(_fromUtf8(""))
        self.lineEdit_S04B.setObjectName(_fromUtf8("lineEdit_S04B"))
        self.lineEdit_S04A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S04A.setGeometry(QtCore.QRect(60, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S04A.setFont(font)
        self.lineEdit_S04A.setText(_fromUtf8(""))
        self.lineEdit_S04A.setObjectName(_fromUtf8("lineEdit_S04A"))
        self.label_27 = QtGui.QLabel(self.tab_7)
        self.label_27.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_7)
        self.label_28.setGeometry(QtCore.QRect(130, 200, 21, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_S05B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S05B.setGeometry(QtCore.QRect(160, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S05B.setFont(font)
        self.lineEdit_S05B.setText(_fromUtf8(""))
        self.lineEdit_S05B.setObjectName(_fromUtf8("lineEdit_S05B"))
        self.lineEdit_S05A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S05A.setGeometry(QtCore.QRect(60, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S05A.setFont(font)
        self.lineEdit_S05A.setText(_fromUtf8(""))
        self.lineEdit_S05A.setObjectName(_fromUtf8("lineEdit_S05A"))
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 250, 51, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_7)
        self.label_30.setGeometry(QtCore.QRect(130, 250, 21, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lineEdit_S06B = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S06B.setGeometry(QtCore.QRect(160, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S06B.setFont(font)
        self.lineEdit_S06B.setText(_fromUtf8(""))
        self.lineEdit_S06B.setObjectName(_fromUtf8("lineEdit_S06B"))
        self.lineEdit_S06A = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_S06A.setGeometry(QtCore.QRect(60, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_S06A.setFont(font)
        self.lineEdit_S06A.setText(_fromUtf8(""))
        self.lineEdit_S06A.setObjectName(_fromUtf8("lineEdit_S06A"))
        self.label_31 = QtGui.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(10, 300, 51, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_7)
        self.label_32.setGeometry(QtCore.QRect(130, 300, 21, 21))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.pushButton_17 = QtGui.QPushButton(self.tab_7)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 360, 111, 31))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.comboBox_4 = QtGui.QComboBox(self.tab_7)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 330, 211, 31))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.pushButton_19 = QtGui.QPushButton(self.tab_7)
        self.pushButton_19.setGeometry(QtCore.QRect(120, 360, 101, 31))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(660, 0, 131, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 20, 131, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 50, 131, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 131, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(0, 70, 131, 26))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 120, 131, 26))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 150, 131, 421))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 30, 111, 41))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setProperty("value", 23.0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setProperty("value", 23.0)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_4.setGeometry(QtCore.QRect(10, 180, 111, 41))
        self.lcdNumber_4.setSmallDecimalPoint(True)
        self.lcdNumber_4.setProperty("value", 23.0)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_6.setGeometry(QtCore.QRect(10, 280, 111, 41))
        self.lcdNumber_6.setSmallDecimalPoint(True)
        self.lcdNumber_6.setProperty("value", 23.0)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 330, 111, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 390, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(70, 370, 53, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 370, 51, 18))
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_5.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.lcdNumber_5.setSmallDecimalPoint(True)
        self.lcdNumber_5.setProperty("value", 23.0)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 130, 111, 41))
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setProperty("value", 23.0)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 500, 411, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.progressBar_r05 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r05.setGeometry(QtCore.QRect(290, 20, 118, 23))
        self.progressBar_r05.setProperty("value", 0)
        self.progressBar_r05.setObjectName(_fromUtf8("progressBar_r05"))
        self.progressBar_r01 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r01.setGeometry(QtCore.QRect(10, 20, 118, 23))
        self.progressBar_r01.setProperty("value", 0)
        self.progressBar_r01.setObjectName(_fromUtf8("progressBar_r01"))
        self.progressBar_r02 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r02.setGeometry(QtCore.QRect(10, 40, 118, 23))
        self.progressBar_r02.setProperty("value", 0)
        self.progressBar_r02.setObjectName(_fromUtf8("progressBar_r02"))
        self.progressBar_r06 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r06.setGeometry(QtCore.QRect(290, 40, 118, 23))
        self.progressBar_r06.setProperty("value", 0)
        self.progressBar_r06.setObjectName(_fromUtf8("progressBar_r06"))
        self.progressBar_r04 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r04.setGeometry(QtCore.QRect(150, 40, 118, 23))
        self.progressBar_r04.setProperty("value", 0)
        self.progressBar_r04.setObjectName(_fromUtf8("progressBar_r04"))
        self.progressBar_r03 = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar_r03.setGeometry(QtCore.QRect(150, 20, 118, 23))
        self.progressBar_r03.setProperty("value", 0)
        self.progressBar_r03.setObjectName(_fromUtf8("progressBar_r03"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 510, 221, 61))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: red"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTeste2 = QtGui.QAction(MainWindow)
        self.actionTeste2.setObjectName(_fromUtf8("actionTeste2"))
        self.actionParte1 = QtGui.QAction(MainWindow)
        self.actionParte1.setCheckable(False)
        self.actionParte1.setObjectName(_fromUtf8("actionParte1"))
        self.actionParte2 = QtGui.QAction(MainWindow)
        self.actionParte2.setCheckable(False)
        self.actionParte2.setChecked(False)
        self.actionParte2.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionParte2.setObjectName(_fromUtf8("actionParte2"))
        self.actionCOM1 = QtGui.QAction(MainWindow)
        self.actionCOM1.setCheckable(True)
        self.actionCOM1.setObjectName(_fromUtf8("actionCOM1"))
        self.actionCOM2 = QtGui.QAction(MainWindow)
        self.actionCOM2.setCheckable(True)
        self.actionCOM2.setObjectName(_fromUtf8("actionCOM2"))
        self.actionCOM3 = QtGui.QAction(MainWindow)
        self.actionCOM3.setCheckable(True)
        self.actionCOM3.setObjectName(_fromUtf8("actionCOM3"))
        self.action_dev_ttyA0 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA0.setCheckable(True)
        self.action_dev_ttyA0.setChecked(True)
        self.action_dev_ttyA0.setObjectName(_fromUtf8("action_dev_ttyA0"))
        self.action_dev_ttyA1 = QtGui.QAction(MainWindow)
        self.action_dev_ttyA1.setCheckable(True)
        self.action_dev_ttyA1.setObjectName(_fromUtf8("action_dev_ttyA1"))
        self.action9600 = QtGui.QAction(MainWindow)
        self.action9600.setCheckable(True)
        self.action9600.setChecked(True)
        self.action9600.setObjectName(_fromUtf8("action9600"))
        self.actionImportar_dados = QtGui.QAction(MainWindow)
        self.actionImportar_dados.setObjectName(_fromUtf8("actionImportar_dados"))
        self.actionEnviar_Arquivos = QtGui.QAction(MainWindow)
        self.actionEnviar_Arquivos.setObjectName(_fromUtf8("actionEnviar_Arquivos"))
        self.actionVideo = QtGui.QAction(MainWindow)
        self.actionVideo.setObjectName(_fromUtf8("actionVideo"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.action11500 = QtGui.QAction(MainWindow)
        self.action11500.setCheckable(True)
        self.action11500.setObjectName(_fromUtf8("action11500"))
        self.actionExportar_como_csv = QtGui.QAction(MainWindow)
        self.actionExportar_como_csv.setObjectName(_fromUtf8("actionExportar_como_csv"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionXLS = QtGui.QAction(MainWindow)
        self.actionXLS.setObjectName(_fromUtf8("actionXLS"))
        self.actionTXT = QtGui.QAction(MainWindow)
        self.actionTXT.setObjectName(_fromUtf8("actionTXT"))
        self.actionNumpy = QtGui.QAction(MainWindow)
        self.actionNumpy.setObjectName(_fromUtf8("actionNumpy"))
        self.action0_5s = QtGui.QAction(MainWindow)
        self.action0_5s.setCheckable(True)
        self.action0_5s.setObjectName(_fromUtf8("action0_5s"))
        self.action1s = QtGui.QAction(MainWindow)
        self.action1s.setCheckable(True)
        self.action1s.setObjectName(_fromUtf8("action1s"))
        self.action1_5s = QtGui.QAction(MainWindow)
        self.action1_5s.setCheckable(True)
        self.action1_5s.setObjectName(_fromUtf8("action1_5s"))
        self.action2s = QtGui.QAction(MainWindow)
        self.action2s.setCheckable(True)
        self.action2s.setChecked(True)
        self.action2s.setObjectName(_fromUtf8("action2s"))
        self.action3s = QtGui.QAction(MainWindow)
        self.action3s.setCheckable(True)
        self.action3s.setObjectName(_fromUtf8("action3s"))
        self.action5s = QtGui.QAction(MainWindow)
        self.action5s.setCheckable(True)
        self.action5s.setObjectName(_fromUtf8("action5s"))
        self.action10s = QtGui.QAction(MainWindow)
        self.action10s.setCheckable(True)
        self.action10s.setObjectName(_fromUtf8("action10s"))
        self.actionCustom = QtGui.QAction(MainWindow)
        self.actionCustom.setObjectName(_fromUtf8("actionCustom"))
        self.actionResolu_o_1 = QtGui.QAction(MainWindow)
        self.actionResolu_o_1.setObjectName(_fromUtf8("actionResolu_o_1"))
        self.actionResolu_o_2 = QtGui.QAction(MainWindow)
        self.actionResolu_o_2.setObjectName(_fromUtf8("actionResolu_o_2"))
        self.actionExclusive = QtGui.QAction(MainWindow)
        self.actionExclusive.setObjectName(_fromUtf8("actionExclusive"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(1)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_7.display)
        QtCore.QObject.connect(self.horizontalSlider_r02, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_r04, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_r06, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_r05, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_r03, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QObject.connect(self.horizontalSlider_r01, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_8.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Esteira", None))
        self.pushButton_4.setText(_translate("MainWindow", "Parar", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Resistências", None))
        self.label_4.setText(_translate("MainWindow", "Superior", None))
        self.label_5.setText(_translate("MainWindow", "Inferior", None))
        self.label_6.setText(_translate("MainWindow", "Esquerda", None))
        self.label_7.setText(_translate("MainWindow", "Centro", None))
        self.label_8.setText(_translate("MainWindow", "Direita", None))
        self.radioButton.setText(_translate("MainWindow", "Hold", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Comando Manual", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Comandos Manuais", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Dados Ubee", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Temperatura", None))
        self.pushButton_6.setText(_translate("MainWindow", "Envia", None))
        self.checkBox.setText(_translate("MainWindow", "Sensor 1", None))
        self.checkBox_2.setText(_translate("MainWindow", "Sensor 2", None))
        self.checkBox_3.setText(_translate("MainWindow", "Sensor 4", None))
        self.checkBox_4.setText(_translate("MainWindow", "Sensor 3", None))
        self.checkBox_5.setText(_translate("MainWindow", "Sensor 6", None))
        self.checkBox_6.setText(_translate("MainWindow", "Sensor 5", None))
        self.checkBox_8.setText(_translate("MainWindow", "Simulação", None))
        self.checkBox_7.setText(_translate("MainWindow", "Esteira", None))
        self.label_9.setText(_translate("MainWindow", "Delta T = 60min", None))
        self.label_10.setText(_translate("MainWindow", "1 min", None))
        self.label_11.setText(_translate("MainWindow", "180 min", None))
        self.checkBox_14.setText(_translate("MainWindow", "Auto", None))
        self.label_16.setText(_translate("MainWindow", "Latência:", None))
        self.pushButton_7.setText(_translate("MainWindow", "LimparTexto", None))
        self.checkBox_20.setText(_translate("MainWindow", "Exp  atual", None))
        self.pushButton_18.setText(_translate("MainWindow", "clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Manual", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Automatico", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Automatico", None))
        self.label_14.setText(_translate("MainWindow", "Refresh (s)", None))
        self.checkBox_10.setText(_translate("MainWindow", "Auto update", None))
        self.checkBox_11.setText(_translate("MainWindow", "Auto Save", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Manual - Imagem", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "2592x1944", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "1296x972", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "1296x730", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "640x480", None))
        self.pushButton_5.setText(_translate("MainWindow", "Tira Foto", None))
        self.label_13.setText(_translate("MainWindow", "Delay (ms)", None))
        self.label_12.setText(_translate("MainWindow", "Resolução", None))
        self.pushButton_9.setText(_translate("MainWindow", "Salva Imagem", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "AutoDetecção", None))
        self.pushButton_10.setText(_translate("MainWindow", "Configurações", None))
        self.checkBox_12.setText(_translate("MainWindow", "Auto Detect", None))
        self.checkBox_13.setText(_translate("MainWindow", "Alerta", None))
        self.label_15.setText(_translate("MainWindow", "PI Camera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Camera", None))
        self.pushButton_8.setText(_translate("MainWindow", "Gerar Arquivo", None))
        self.pushButton_11.setText(_translate("MainWindow", "Enviar e-mail", None))
        self.pushButton_12.setText(_translate("MainWindow", "Pendrive", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Formato", None))
        self.checkBox_15.setText(_translate("MainWindow", ".txt", None))
        self.checkBox_16.setText(_translate("MainWindow", ".csv (excel)", None))
        self.pushButton_13.setText(_translate("MainWindow", "Zerar Banco", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "E-mail  -  (gmail)", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "e-mail@gmail.com", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Senha", None))
        self.pushButton_14.setText(_translate("MainWindow", "Limpar senha e e-mail", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Experimento", None))
        self.checkBox_18.setText(_translate("MainWindow", "periodo", None))
        self.checkBox_19.setText(_translate("MainWindow", "Atual", None))
        self.label_19.setText(_translate("MainWindow", "Exp Atual:", None))
        self.label_20.setText(_translate("MainWindow", "Sem Nome", None))
        self.pushButton_15.setText(_translate("MainWindow", "Novo Experimento", None))
        self.pushButton_16.setText(_translate("MainWindow", "Local do Arquivo", None))
        self.label_17.setText(_translate("MainWindow", "T( d ) =  A  +  B *  d", None))
        self.label_21.setText(_translate("MainWindow", "S1: A =", None))
        self.label_22.setText(_translate("MainWindow", "B =", None))
        self.label_23.setText(_translate("MainWindow", "S2: A =", None))
        self.label_24.setText(_translate("MainWindow", "B =", None))
        self.label_25.setText(_translate("MainWindow", "S3: A =", None))
        self.label_26.setText(_translate("MainWindow", "B =", None))
        self.label_27.setText(_translate("MainWindow", "S4: A =", None))
        self.label_28.setText(_translate("MainWindow", "B =", None))
        self.label_29.setText(_translate("MainWindow", "S5: A =", None))
        self.label_30.setText(_translate("MainWindow", "B =", None))
        self.label_31.setText(_translate("MainWindow", "S6: A =", None))
        self.label_32.setText(_translate("MainWindow", "B =", None))
        self.pushButton_17.setText(_translate("MainWindow", "Salvar", None))
        self.pushButton_19.setText(_translate("MainWindow", "deletar", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Linear", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Polinomial", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Dados", None))
        self.groupBox.setTitle(_translate("MainWindow", "Conexão", None))
        self.pushButton.setText(_translate("MainWindow", "Conectar", None))
        self.label.setText(_translate("MainWindow", "Porta:", None))
        self.label_2.setText(_translate("MainWindow", "BaudRate", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "57600", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "115200", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sensores", None))
        self.pushButton_2.setText(_translate("MainWindow", "Atualiza", None))
        self.label_3.setText(_translate("MainWindow", "Latência:", None))
        self.checkBox_9.setText(_translate("MainWindow", "Auto", None))
        self.groupBox_3.setTitle(_translate("MainWindow", " Esquerda                            Potencia Resistências                           Direita", None))
        self.pushButton_3.setText(_translate("MainWindow", "Emergência", None))
        self.actionTeste2.setText(_translate("MainWindow", "Imprimir", None))
        self.actionParte1.setText(_translate("MainWindow", "Salvar Configuração", None))
        self.actionParte2.setText(_translate("MainWindow", "Restaurar Padrão", None))
        self.actionCOM1.setText(_translate("MainWindow", "COM1", None))
        self.actionCOM2.setText(_translate("MainWindow", "COM2", None))
        self.actionCOM3.setText(_translate("MainWindow", "COM3", None))
        self.action_dev_ttyA0.setText(_translate("MainWindow", "/dev/ttyA0", None))
        self.action_dev_ttyA1.setText(_translate("MainWindow", "/dev/ttyA1", None))
        self.action9600.setText(_translate("MainWindow", "9600", None))
        self.actionImportar_dados.setText(_translate("MainWindow", "Importar dados", None))
        self.actionEnviar_Arquivos.setText(_translate("MainWindow", "Enviar Arquivos", None))
        self.actionVideo.setText(_translate("MainWindow", "Video", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.action11500.setText(_translate("MainWindow", "11500", None))
        self.actionExportar_como_csv.setText(_translate("MainWindow", "Exportar como csv", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionXLS.setText(_translate("MainWindow", "XLS", None))
        self.actionTXT.setText(_translate("MainWindow", "TXT", None))
        self.actionNumpy.setText(_translate("MainWindow", "Numpy", None))
        self.action0_5s.setText(_translate("MainWindow", "0.5s", None))
        self.action1s.setText(_translate("MainWindow", "1s", None))
        self.action1_5s.setText(_translate("MainWindow", "1.5s", None))
        self.action2s.setText(_translate("MainWindow", "2s", None))
        self.action3s.setText(_translate("MainWindow", "3s", None))
        self.action5s.setText(_translate("MainWindow", "5s", None))
        self.action10s.setText(_translate("MainWindow", "10s", None))
        self.actionCustom.setText(_translate("MainWindow", "Outro ...", None))
        self.actionResolu_o_1.setText(_translate("MainWindow", "Resolução 1", None))
        self.actionResolu_o_2.setText(_translate("MainWindow", "Resolução 2", None))
        self.actionExclusive.setText(_translate("MainWindow", "exclusive", None))

from matplotlibwidgetFile import matplotlibWidget
